config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員用
  root 'public/homes#top'
  get 'about', to: 'public/homes#about', as: 'about'

  namespace :public do

    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'list', to: 'customers#index', as: 'list'
      end
      member do
        get 'profile', to: 'customers#show', as: 'profile'
        get 'profile/edit', to: 'customers#edit', as: 'profile/edit'
        patch 'profile', to: 'customers#update'
        get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
        patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'

        get :favorites
      end
    end

    # Public Posts
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # Public Groups
    resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :group_requests, only: [:create, :update, :destroy]
    end

    resources :genres, only: [:index, :show]
    #get 'genres', to: 'genres#index', as: 'genres'

    # Public Searches
    get 'searches/search', to: 'searches#search', as: 'search'

    # Public Static Pages
    get 'static_pages/terms', to: 'static_pages#terms'
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'

    # Admin Sessions
    resources :sessions, only: [:new, :create, :destroy]

    # Admin Posts
    resources :posts, only: [:index, :show, :delete]

    #Admin Post_comments
    resources :post_comments, only: [:index, :show, :destroy]

    # Admin Genres
    resources :genres, only: [:index, :create, :edit, :update]

    # Admin Customers
    resources :customers, only: [:index, :show, :update]

    # Admin Groups
    resources :groups, only: [:index, :show, :destroy]

    # Admin Searches
    get 'searches/search', to: 'searches#search', as: 'search'

    # Admin Static Pages
    get 'static_pages/terms', to: 'static_pages#terms'
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  #validates :name, uniqueness: true, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを登録しました"
    else
      flash.now[:notice] = "登録に失敗しました"
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを更新しました"
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :introduction)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">

  <h3 class="text-center mt-5">ジャンル編集</h3>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @genre, url: admin_genre_path(@genre), method: :patch, class: 'form-group') do |f| %>
        <%= f.label :name, "ジャンル名", class: 'form-label' %>
        <div class="row input-group mb-3">
          <%= f.text_field :name, class: 'form-control', placeholder: 'ジャンル名を入力してください' %>
        </div>
        <%= f.label :introduction, "紹介文", class: 'form-label' %>
        <div class="row input-group mb-3">
          <%= f.text_field :introduction, class: 'form-control', placeholder: 'ジャンルについて入力してください' %>
        </div>
        <div class="row input-group-append">
          <div class="mx-auto">
            <%= f.submit "更新", class: 'btn btn-info' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/genres/index.html.erb
<div class="text-center h3 mb-5 py-3">
  ジャンル一覧・追加
</div>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @genre, url: admin_genres_path, class: 'form-group') do |f| %>
        <%= f.label :name, "ジャンル名", class: 'form-label' %>
        <div class="input-group mb-3">
          <%= f.text_field :name, class: 'form-control', placeholder: 'ジャンル名を入力してください' %>
        </div>
        <%= f.label :introduction, "ジャンル紹介文", class: 'form-label' %>
        <div class="input-group mb-3">
          <%= f.text_field :introduction, class: 'form-control', placeholder: 'ジャンル名を入力してください' %>
        </div>
        <div class="input-group-append">
          <%= f.submit "新規登録", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center py-5">
    <div class="col-md-8">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ジャンル名</th>
            <th>紹介文</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= genre.introduction %></td>
              <td><%= link_to '編集', edit_admin_genre_path(genre), class: 'btn btn-success' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>