config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員用
  root 'public/homes#top'
  get 'about', to: 'public/homes#about', as: 'about'

  namespace :public do

    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'list', to: 'customers#index', as: 'list'
      end
      member do
        get 'profile', to: 'customers#show', as: 'profile'
        get 'profile/edit', to: 'customers#edit', as: 'profile/edit'
        patch 'profile', to: 'customers#update'
        get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
        patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'

        get :favorites
      end
    end

    # Public Posts
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # Public Groups
    resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :group_requests, only: [:create, :update, :destroy]
    end

    resources :genres, only: [:index, :show]
    #get 'genres', to: 'genres#index', as: 'genres'

    # Public Searches
    get 'searches/search', to: 'searches#search', as: 'search'

    # Public Static Pages
    get 'static_pages/terms', to: 'static_pages#terms'
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'

    # Admin Sessions
    resources :sessions, only: [:new, :create, :destroy]

    # Admin Posts
    resources :posts, only: [:index, :show, :delete]

    #Admin Post_comments
    resources :post_comments, only: [:index, :show, :destroy]

    # Admin Genres
    resources :genres, only: [:index, :create, :edit, :update]

    # Admin Customers
    resources :customers, only: [:index, :show, :update]

    # Admin Groups
    resources :groups, only: [:index, :show, :destroy]

    # Admin Searches
    get 'searches/search', to: 'searches#search', as: 'search'

    # Admin Static Pages
    get 'static_pages/terms', to: 'static_pages#terms'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :group_requests, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :groups, dependent: :destroy #会員id(オーナーの取得)
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'profile_image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :introduction, length: { maximum: 500 }
  validates :email, presence: true

  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

  def guest_customer?
    email == GUEST_CUSTOMER_EMAIL
  end

  #is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end

  def self.search_for(word)
    where('name LIKE ?', "%#{word}%")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  #validates :name, uniqueness: true, presence: true
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :customers, through: :group_users, dependent: :destroy
  has_many :group_requests, dependent: :destroy

  belongs_to :owner, class_name: 'Customer', foreign_key: 'owner_id' #会員id(オーナー)の取得
  belongs_to :genre

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :introduction, presence: true, length: { minimum: 10, maximum: 500 }
  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'profile_image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  # def is_owned_by?(customers)
  #   owner.id == customers.id
  # end

end

app/models/group_request.rb
class GroupRequest < ApplicationRecord
  belongs_to :customer
  belongs_to :group

  enum is_status: { pending: 0, approved: 1, rejected: 2 }

  validates :is_status, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :customer
  
  def includesCustomer?(customer)
    group_users.exists?(customer_id: customer.id)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :genre

  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :tags, dependent: :destroy

  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }

  has_many_attached :images

  validates :title, presence: true, length: { maximum: 100 }
  validates :introduction, presence: true, length: { maximum: 2000 }
  validates :genre_id, presence: true

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def self.search_for(word)
    where('title LIKE ?', "%#{word}%")
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true, length: { minimum: 1, maximum: 500 }

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @posts = Post.all.page(params[:page]).per(9)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.find(params[:id])
    @post_comments = @post.post_comments.all.page(params[:page]).per(9).order(created_at: :desc)
    @total_comments_count = @post.post_comments.count
  end

  private

  def post_params
    params.require(:post).permit(:title, :introduction, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/index.html.erb
<h1>Admin::Posts#index</h1>
<p>Find me in app/views/admin/posts/index.html.erb</p>

app/views/admin/posts/show.html.erb
<div class="text-center h3 mb-5 py-3", style="background: #EBF1F5;">
  投稿詳細
</div>

<div class="container">

  <div class="row flame-border p-3">
    <div class="col">

      <div class="row border-bottom">
        <div class="col-1 p-3">
          <p class="">
            <%= link_to admin_customer_path(@post.customer), style:"text-decoration: none;" do %>
              <%= image_tag @post.customer.get_profile_image(50,50), class:"icon" %>
            <% end %>
          </p>
        </div>
        <div class="col-11">
          <p class=""><%= @post.customer.name %></p>
          <p class=""><%= @post.created_at.strftime('%Y/%m/%d') %></p>
        </div>
      </div>

      <div class="row border-bottom my-3">
        <div class="col mx-auto">
          <p class="">ジャンル：<%= @post.genre.name %></p>
          <p class="col text-center text-wrap h3 py-3"><%= @post.title %></p>
          <p class="text-wrap py-3"><%= @post.introduction %></p>
        </div>
      </div>



      <div class="row p-3">
          <%#= link_to "削除する", admin_post_path(@post), method: :delete, class:"btn btn-danger ml-3" %>
      </div>

    </div>
  </div>

  <div class="row flame-border my-3 p-3">
    <div class="col">

      <p>コメント件数：<%= @total_comments_count %></p>
      <% @post_comments.each do |post_comment| %>
        <div class="row">
          <div class="co-2 my-3 p-3">
            <%= link_to admin_customer_path(post_comment.customer), style:"text-decoration: none;" do %>
              <%= image_tag post_comment.customer.get_profile_image(50,50), class:"icon" %>
            <% end %>
          </div>
          <div class="col-10 my-3 p-3", style="background: #EBF1F5; border-radius: 8px;" >

            <div>
              <%= post_comment.customer.name %>
              <p class="text-wrap"><%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
              <p class="text-wrap border-bottom py-3"><%= post_comment.comment %></p>

              <%= link_to "削除", admin_post_comment_path(post_comment), method: :delete, class: "btn btn-danger" %>
              <%= link_to "詳細へ", admin_post_comment_path(post_comment), class: "btn btn-info ml-3" %>

            </div>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col d-flex justify-content-center">
          <%= paginate @post_comments, theme: 'bootstrap-5' %>
        </div>
      </div>

    </div>
  </div>

</div>