config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員用
  root 'public/homes#top'
  get 'about', to: 'public/homes#about', as: 'about'

  namespace :public do

    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'list', to: 'customers#index', as: 'list'
      end
      member do
        get 'profile', to: 'customers#show', as: 'profile'
        get 'profile/edit', to: 'customers#edit', as: 'profile/edit'
        patch 'profile', to: 'customers#update'
        get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
        patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'

        get :favorites
      end
    end

    # Public Posts
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # Public Groups
    resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :group_requests, only: [:create, :update, :destroy]
    end

    resources :genres, only: [:index, :show]
    #get 'genres', to: 'genres#index', as: 'genres'

    # Public Searches
    get 'searches/search', to: 'searches#search', as: 'search'

    # Public Static Pages
    get 'static_pages/terms', to: 'static_pages#terms'
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'

    # Admin Sessions
    resources :sessions, only: [:new, :create, :destroy]

    # Admin Posts
    resources :posts, only: [:index, :show, :delete]

    #Admin Post_comments
    resources :post_comments, only: [:index, :show, :destroy]

    # Admin Genres
    resources :genres, only: [:index, :create, :edit, :update]

    # Admin Customers
    resources :customers, only: [:index, :show, :update]

    # Admin Groups
    resources :groups, only: [:index, :show, :destroy]

    # Admin Searches
    get 'searches/search', to: 'searches#search', as: 'search'

    # Admin Static Pages
    get 'static_pages/terms', to: 'static_pages#terms'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :group_requests, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :groups, dependent: :destroy #会員id(オーナーの取得)
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'profile_image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :introduction, length: { maximum: 500 }
  validates :email, presence: true

  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

  def guest_customer?
    email == GUEST_CUSTOMER_EMAIL
  end

  #is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end

  def self.search_for(word)
    where('name LIKE ?', "%#{word}%")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  #validates :name, uniqueness: true, presence: true
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :customers, through: :group_users, dependent: :destroy
  has_many :group_requests, dependent: :destroy

  belongs_to :owner, class_name: 'Customer', foreign_key: 'owner_id' #会員id(オーナー)の取得
  belongs_to :genre

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :introduction, presence: true, length: { minimum: 10, maximum: 500 }
  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'profile_image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  # def is_owned_by?(customers)
  #   owner.id == customers.id
  # end

end

app/models/group_request.rb
class GroupRequest < ApplicationRecord
  belongs_to :customer
  belongs_to :group

  enum is_status: { pending: 0, approved: 1, rejected: 2 }

  validates :is_status, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :customer
  
  def includesCustomer?(customer)
    group_users.exists?(customer_id: customer.id)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :genre

  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :tags, dependent: :destroy

  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }

  has_many_attached :images

  validates :title, presence: true, length: { maximum: 100 }
  validates :introduction, presence: true, length: { maximum: 2000 }
  validates :genre_id, presence: true

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def self.search_for(word)
    where('title LIKE ?', "%#{word}%")
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true, length: { minimum: 1, maximum: 500 }

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="container">
    <div class="row my-5">
      <div class="col">
        <p class="text-muted">Place sticky footer content here.</p>
        <% unless admin_signed_in? %>
          <div><%= link_to "利用規約", public_static_pages_terms_path, class: "text-muted" %></div>
        <% else %>
          <div><%= link_to "利用規約", admin_static_pages_terms_path, class: "text-muted" %></div>
        <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">

            <% if customer_signed_in? %>
              <%= link_to public_posts_path, class:"navbar-brand p-3" do %>
              <%= image_tag "logo.png", size:'200x80'%>
              <%= image_tag "logo2.png", size:'80x80'%>
              <% end %>
            <% elsif admin_signed_in? %>
              <%= link_to admin_root_path, class:"navbar-brand p-3" do %>
              <%= image_tag "logo.png", size:'200x80'%>
              <% end %>
            <% else %>
              <%= link_to root_path, class:"navbar-brand p-3" do %>
              <%= image_tag "logo.png", size:'200x80'%>
              <% end %>
            <% end %>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto d-flex align-items-center">
            <% if customer_signed_in? %>

            <!--会員がログインしている時 -->
              <div class="search_form">
                  <%= form_with url: public_search_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word %>
                    <%= f.select :model, options_for_select([['customer'], ['post']]) %>
                    <%= button_tag type: "submit", class: "search-btn", style:"width: 50px;" do %>
                      <i class="fas fa-search"></i>
                    <% end %>
                  <% end %>
              </div>
              <li class="nav-item mx-2 ">
                <%= link_to  destroy_customer_session_path, class: "header-btn",style:"width: 50px;", method: :delete do %>
                  <i class="fa-solid fa-arrow-right-from-bracket "></i>
                <% end %>
              </li>
              <li class="nav-item font-weight-bold mx-2 small">
                <%= truncate(current_customer.name, length: 9) %>
              </li>
              <li class="nav-item mx-2">
                <%= link_to public_customer_path(current_customer) do %>
                  <%= image_tag current_customer.get_profile_image(50,50), class:"icon" %>
                <% end %>
              </li>
              <% unless current_customer.guest_customer? %>
                <li class="nav-item mx-2" >
                  <%= link_to "投稿する", new_public_post_path, class: "header-btn-fill", style:"width: 80px; text-decoration: none;" %>
                </li>
              <% end %>
            <% elsif admin_signed_in? %>
              <!-- 管理者がログインしている時 -->
              <li class="nav-item me-auto p-2">
                管理者画面です
              </li>
              <li class="nav-item ">
                <%= link_to destroy_admin_session_path, class: "header-btn" , method: :delete do %>
                  <i class="fa-solid fa-arrow-right-from-bracket "></i>
                <% end %>
              </li>
            <% else %>
              <!-- ログインしていない時 -->
              <li class="nav-item mx-2">
                <%= link_to "新規登録", new_customer_registration_path, class: "header-btn-fill",style:"width: 100px; text-decoration: none;" %>
              </li>
              <li class="nav-item mx-2">
                <%= link_to "ログイン", new_customer_session_path, class: "header-btn-fill",style:"width: 100px; text-decoration: none;" %>
              </li>
            <% end %>
          </ul>
          <%#= form_with class: 'd-flex' do |f| %>
            <%#= f.text_field :content, placeholder: "検索..." %>
            <%#= f.submit '検索', class: 'ml-1 btn btn-outline-warning flex-shrink-0' %>
          <%# end %>

        </div>
      </div>
  </nav>

  <nav class="navbar navbar-light bg-light">
    <div class="container">
      <div class="mx-auto">
          <ul class="mb-0 d-flex align-items-center list-unstyled text-nowrap">
            <% if customer_signed_in? %>

            <!--会員がログインしている時 -->
              <li class="navbar-brand pr-4 border-right" >
                <%= link_to "会員一覧", list_public_customers_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right" >
                <%= link_to "グループ一覧", public_groups_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "ジャンル一覧", public_genres_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "About", about_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "いいね一覧", favorites_public_customer_path(current_customer.id), class: "text-dark" %>
              </li>
            <% elsif admin_signed_in? %>
              <!-- 管理者がログインしている時 -->
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "会員一覧", admin_customers_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "グループ一覧", admin_groups_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "ジャンル一覧", admin_genres_path, class: "text-dark" %>
              </li>
              <li class="navbar-brand pr-4 border-right">
                <%= link_to "コメント一覧", admin_post_comments_path, class: "text-dark" %>
              </li>
            <% else %>
              <!-- ログインしていない時 -->
              <li class="navbar-brand pr-4">
                <%= link_to "About", about_path, class: "text-dark"  %>
              </li>
            <% end %>
          </ul>
         </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaku10</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/34c28f9202.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main class ="mb-auto">
      <div>
        <% flash.each do |message_type, message| %>
          <div class="flash-message <%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>